export enum EquipementStatus {
//ACTIVE ='ACTIVE', OBSOLETE='OBSOLETE', OUT_OF_SERVICE='OUT_OF_SERVICE'



ACTIVE='ACTIVE' , BROKEN='BROKEN', UNDER_REPAIR='UNDER_REPAIR', OUT_OF_SERVICE='OUT_OF_SERVICE'

}
